// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TCMB.DATA.Context;

namespace TCMB.DATA.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20221111123949_addTablesCurrency5")]
    partial class addTablesCurrency5
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 63)
                .HasAnnotation("ProductVersion", "5.0.17")
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

            modelBuilder.Entity("TCMB.DATA.Models.AppUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.ToTable("AppUser");
                });

            modelBuilder.Entity("TCMB.DATA.Models.RequestData", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<int>("Ay")
                        .HasColumnType("integer");

                    b.Property<int>("Gun")
                        .HasColumnType("integer");

                    b.Property<int>("Yil")
                        .HasColumnType("integer");

                    b.Property<bool>("isBugun")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.ToTable("RequestData");
                });

            modelBuilder.Entity("TCMB.DATA.Models.ResponseData", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("Hata")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("ResponseDatas");
                });

            modelBuilder.Entity("TCMB.DATA.Models.ResponseDataKur", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("Adi")
                        .HasColumnType("text");

                    b.Property<decimal>("AlisKuru")
                        .HasColumnType("numeric");

                    b.Property<int>("Birimi")
                        .HasColumnType("integer");

                    b.Property<decimal>("EfektifAlisKuru")
                        .HasColumnType("numeric");

                    b.Property<decimal>("EfektifSatisKuru")
                        .HasColumnType("numeric");

                    b.Property<string>("Kodu")
                        .HasColumnType("text");

                    b.Property<int?>("ResponseDataId")
                        .HasColumnType("integer");

                    b.Property<decimal>("SatisKuru")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("ResponseDataId");

                    b.ToTable("ResponseDataKurs");
                });

            modelBuilder.Entity("TCMB.DATA.Models.ResponseDataKur", b =>
                {
                    b.HasOne("TCMB.DATA.Models.ResponseData", null)
                        .WithMany("Data")
                        .HasForeignKey("ResponseDataId");
                });

            modelBuilder.Entity("TCMB.DATA.Models.ResponseData", b =>
                {
                    b.Navigation("Data");
                });
#pragma warning restore 612, 618
        }
    }
}
